pull_request_rules:
  - name: Automatic approve on Dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatically merge Dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      #This does not seem to be working anymore: - '#commits-behind=0' # Only merge up to date pull requests
      - check-success=connected_check
      - check-success=check
      - check-success=Codacy Static Code Analysis
      - check-success=license/cla
    actions:
      merge:
        method: merge