name: Run Connected Checks

on: push

jobs:
  connected_check:

    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28] #wait with this until tests are more stable 33

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Run Connected Checks
        id: testing
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          disk-size: 8G
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -memory 5120
          script: |
            adb logcat -c                             # clear logs, delete any existing pictures
            mkdir app
            touch app/emulator.log                    # create log file
            chmod 777 app/emulator.log                # allow writing to log file
            adb logcat >> app/emulator.log &          # pipe all logcat messages into log file as a background process
            ./gradlew connectedCheck
          
      - name: Upload Failing Test Report Log
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: appData
          path: app/  # path to where all logs and screenshots are
