name: Run Checks

on: push

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Run Checks with Gradle
        run: ./gradlew check
