name: Run Connected Checks

on: push

jobs:
  connected_check:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run Connected Checks
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 4096
          script: ./gradlew connectedCheck
      - name: Upload unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: /Users/runner/work/swedbank-pay-sdk-android/swedbank-pay-sdk-android/mobilesdk-merchantbackend/build/reports/androidTests/connected/index.html
          
