name: Run Connected Checks

on: push

jobs:
  connected_check:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Run Connected Checks
        id: testing
        uses: reactivecircus/android-emulator-runner@v2
        #continue-on-error: true # This does not work
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -memory 5120
          script: |
            adb logcat -c                             # clear logs, delete any existing pictures
            adb shell "rm -rf /sdcard/Android/data/com.swedbankpay.mobilesdk.merchantbackend.test/files/Pictures/*"
            mkdir app
            touch app/emulator.log                    # create log file
            chmod 777 app/emulator.log                # allow writing to log file
            adb logcat >> app/emulator.log &          # pipe all logcat messages into log file as a background process
            
            #gradleResult=$(./gradlew connectedCheck 2>&1)      # supress errors didn't work
            if ./gradlew connectedCheck; then      
                echo "Gradle task succeeded"
            else 
                exitcode=$?
                echo "Gradle task failed"
                # copy any screenshots if exists, silencing the error when there are no screenshots
                adb pull /sdcard/Android/data/com.swedbankpay.mobilesdk.merchantbackend.test/files/Pictures app 2>&1
                
                # exit with the code from the testrun
                exit ${exitcode}
            fi
          
      - name: Upload Failing Test Report Log
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: appData
          path: app/  # path to where all logs and screenshots are
