name: Run Connected Checks

on: push

jobs:
  connected_check:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run Connected Checks
        id: testing
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -memory 5120
          script: |
            adb logcat -c                             # clear logs
            # working dir is: /Users/runner/work/swedbank-pay-sdk-android/swedbank-pay-sdk-android
            mkdir app
            touch app/emulator.log                    # create log file
            chmod 777 app/emulator.log                # allow writing to log file
            adb logcat >> app/emulator.log &          # pipe all logcat messages into log file as a background process
            ./gradlew connectedCheck                  # here run your tests  
      
      - name: Upload Failing Test Report Log
        if: ${{ always() }}
        #if: steps.testing.outcome != 'success'        # upload the generated log on failure of the tests job
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: app/emulator.log # path to where the log is

      - name: Raise error on test fail # set a red tick on the workflow run if the tests failed
        if: steps.testing.outcome != 'success'
        run: exit 1
          
